### PR TITLE
Updated The YAST to Go Version 1.19

### PR DESCRIPTION
**Pull request by Hirdey-1999**
YAST Project has been Updated to 1.19 
Changes made to

### CODE REVIEW

**Review by qascade — CHANGES_REQUESTED** [review]
Can you also bump up the gofmt-lint workflow version. Check out the .workflows folder

**Comment by qascade** [comment]
Once you are done with the same. I will pull the branch and check locally. If everything looks fine. I will merge the PR. Thanks.

**Comment by Hirdey-1999** [comment]
where to find the workflow folder

**Comment by qascade** [comment]
@Hirdey-1999 the checks are failing. Can you run `gofmt` as instructed in the contributing guidelines and push a new commit.

**Comment by qascade** [comment]
Hey, I noticed that you did the changes on the main branch and made a PR. That is not allowed as per yast branching rules and contibution guidelines, can you shift the changes to another branch and make another PR. Also, I don't know but somehow `gofmt CI with version 1.8` is still trying to run and is not finishing making it impossible to merge your PR even if I want to.

**Comment by qascade** [comment]
Closing this PR for now. Please make another PR whenever you get time. I'll approve it.

**Pull request closed without merging**
