### PR TITLE
Trying out bubbles/list for displaying Movie Results

### PR DESCRIPTION
**Pull request by qascade**
Renaming branch name from `bubbletea` to `tui` for better context.

### CODE REVIEW

**Comment by qascade** [comment]
https://github.com/qascade/yast/pull/4

Previous PR.

**Comment by qascade** [comment]
You can run the tests and see the rendered view by following these steps: 
1. go to `yast/ui_tests`
2. Run command `go test -v`.

**Comment by qascade** [comment]
Please Note, that the filtering is yet to be implemented so might break the view. The broken view can be restored by pressing `Esc`

**Comment by qascade** [comment]
Now realising that the branch should have been renamed to something like `tui-listmodel`.

**Review by tiklup11 — APPROVED** [review]

**Review by tiklup11 — CHANGES_REQUESTED** [review]
test comments

**Review by tiklup11 — APPROVED** [review]

**Pull request merged**
