### PR TITLE
Ask the user to choose a player until he finally chooses

### PR DESCRIPTION
**Pull request by murugesanp**
Solves the issue https://github.com/qascade/yast/issues/36

### CODE REVIEW

**Comment by qascade** [comment]
So, Like as per the PR description, what if the person just wants to quit the program and want to do the setup later. Did you write a fallback mechanism for that case?? The point was that config was still getting created with empty string if the person doesnot choose a player but a `config.json` gets created in `~/.yast` directory. What I want is that this file should not be created if the player does not choose a player.

**Review by qascade — CHANGES_REQUESTED** [review]
I have added some comments, please check do the changes accordingly.

**Comment by murugesanp** [comment]
The fix i have made is that as you mentioned in option2 (We can refresh the model to ask the user to choose a player until he finally chooses.). So, this will not allow user to quit the model without choosing the player.

**Comment by qascade** [comment]
I also mentioned the deletion behaviour just below option2 as well.

**Comment by murugesanp** [comment]
Got it @qascade. Will work on it

**Pull request closed without merging**
