### PR TITLE
changing search command description

### PR DESCRIPTION
**Pull request by katarzynakawala**
replacing the default description with the actual one

### CODE REVIEW

**Comment by katarzynakawala** [comment]
Hi, I really like the project and would like to contribute to it. Hope that you don't mind. If this description was there on purpose, please close PR. Thanks!

**Comment by qascade** [comment]
@katarzynakawala sorry for the delayed response, I was very busy with college work, so didnot notice the pr. Let me review this today and get back to you.

**Review by qascade — APPROVED** [review]
Thanks for these changes. LGTM

**Comment by qascade** [comment]
@katarzynakawala Thanks for liking my project. Please feel free to go through the code-base and contibutions.md file and design docs mentioned at the end of the project description. Thanks for this PR.

**Comment by katarzynakawala** [comment]
Hi @qascade Thanks for accepting!

**Pull request merged**
